# MyBatis DOM 파서 전용 규칙 정의
# 이 파일은 MyBatis XML의 구조(DOM)를 해석하기 위한 규칙을 정의합니다.

# 지능형 태그 시뮬레이션 규칙
intelligent_tags:
  where:
    prefix: "WHERE"
    # AND, OR 로 시작하는 경우 해당 키워드를 제거
    prefix_overrides: 
      - "AND "
      - "OR "
    suffix_overrides: []
  set:
    prefix: "SET"
    prefix_overrides: []
    # 쉼표(,)로 끝나는 경우 해당 쉼표를 제거
    suffix_overrides:
      - ","

# <foreach> 구문 재구성 시 사용할 샘플 데이터
sample_data:
  default:
    # 데이터 타입이 확인되지 않을 때 사용할 기본값
    string: 
      - "'sample_val_1'"
      - "'sample_val_2'"
    integer: 
      - "1"
      - "2"
    # 향후 DB 스키마 연동 시, 컬럼 타입에 맞는 샘플 데이터 생성 가능
    # 예:
    # number: [1001, 1002]
    # date: ['2025-01-01', '2025-12-31']
