# Oracle SQL 키워드 정의 파일 (리뉴얼)
# Oracle Database SQL Language Reference 기반 키워드 정의
# 메뉴얼 기반으로 체계적으로 재구성

# Oracle SQL 예약어
oracle_sql_keywords:
  # DDL (Data Definition Language)
  ddl_keywords:
    - "CREATE"
    - "ALTER"
    - "DROP"
    - "TRUNCATE"
    - "RENAME"
    - "COMMENT"
    - "GRANT"
    - "REVOKE"
    - "FLASHBACK"
    - "PURGE"
  
  # DML (Data Manipulation Language)
  dml_keywords:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
    - "MERGE"
    - "CALL"
    - "EXPLAIN"
    - "LOCK"
  
  # DCL (Data Control Language)
  dcl_keywords:
    - "GRANT"
    - "REVOKE"
    - "COMMIT"
    - "ROLLBACK"
    - "SAVEPOINT"
    - "SET"
    - "TRANSACTION"
  
  # 조인 관련
  join_keywords:
    - "JOIN"
    - "INNER"
    - "LEFT"
    - "RIGHT"
    - "FULL"
    - "OUTER"
    - "CROSS"
    - "NATURAL"
    - "USING"
    - "ON"
  
  # 조건절
  condition_keywords:
    - "WHERE"
    - "HAVING"
    - "GROUP"
    - "ORDER"
    - "BY"
    - "ASC"
    - "DESC"
    - "DISTINCT"
    - "UNION"
    - "ALL"
    - "INTERSECT"
    - "MINUS"
    - "EXCEPT"
  
  # 연산자
  operator_keywords:
    - "AND"
    - "OR"
    - "NOT"
    - "IN"
    - "EXISTS"
    - "BETWEEN"
    - "LIKE"
    - "IS"
    - "NULL"
    - "CASE"
    - "WHEN"
    - "THEN"
    - "ELSE"
    - "END"
    - "ANY"
    - "SOME"
    - "ALL"
  
  # Oracle 특화 키워드
  oracle_specific_keywords:
    - "ROWNUM"
    - "ROWID"
    - "DUAL"
    - "SYSDATE"
    - "SYSTIMESTAMP"
    - "USER"
    - "LEVEL"
    - "CONNECT"
    - "PRIOR"
    - "START"
    - "WITH"
    - "RECURSIVE"
    - "PIVOT"
    - "UNPIVOT"
    - "MODEL"
    - "PARTITION"
    - "OVER"
    - "WINDOW"
    - "RANGE"
    - "ROWS"
    - "PRECEDING"
    - "FOLLOWING"
    - "CURRENT"
    - "UNBOUNDED"

# Oracle SQL 함수
oracle_sql_functions:
  # 집계 함수
  aggregate_functions:
    - "COUNT"
    - "SUM"
    - "AVG"
    - "MIN"
    - "MAX"
    - "STDDEV"
    - "VARIANCE"
    - "STDDEV_POP"
    - "STDDEV_SAMP"
    - "VAR_POP"
    - "VAR_SAMP"
    - "COVAR_POP"
    - "COVAR_SAMP"
    - "CORR"
    - "REGR_SLOPE"
    - "REGR_INTERCEPT"
    - "REGR_COUNT"
    - "REGR_R2"
    - "REGR_AVGX"
    - "REGR_AVGY"
    - "REGR_SXX"
    - "REGR_SYY"
    - "REGR_SXY"
    - "LISTAGG"
    - "WM_CONCAT"
  
  # 분석 함수
  analytical_functions:
    - "RANK"
    - "DENSE_RANK"
    - "ROW_NUMBER"
    - "LAG"
    - "LEAD"
    - "FIRST_VALUE"
    - "LAST_VALUE"
    - "NTH_VALUE"
    - "NTILE"
    - "PERCENT_RANK"
    - "CUME_DIST"
    - "PERCENTILE_CONT"
    - "PERCENTILE_DISC"
    - "RATIO_TO_REPORT"
    - "LISTAGG"
  
  # 문자열 함수
  string_functions:
    - "SUBSTR"
    - "SUBSTRING"
    - "LENGTH"
    - "LEN"
    - "UPPER"
    - "LOWER"
    - "INITCAP"
    - "TRIM"
    - "LTRIM"
    - "RTRIM"
    - "REPLACE"
    - "TRANSLATE"
    - "INSTR"
    - "LPAD"
    - "RPAD"
    - "SOUNDEX"
    - "ASCII"
    - "CHR"
    - "CONCAT"
    - "REGEXP_SUBSTR"
    - "REGEXP_REPLACE"
    - "REGEXP_INSTR"
    - "REGEXP_LIKE"
    - "REGEXP_COUNT"
  
  # 날짜 함수
  date_functions:
    - "SYSDATE"
    - "SYSTIMESTAMP"
    - "CURRENT_DATE"
    - "CURRENT_TIMESTAMP"
    - "LOCALTIMESTAMP"
    - "TO_CHAR"
    - "TO_DATE"
    - "TO_TIMESTAMP"
    - "ADD_MONTHS"
    - "MONTHS_BETWEEN"
    - "LAST_DAY"
    - "NEXT_DAY"
    - "EXTRACT"
    - "TRUNC"
    - "ROUND"
    - "NEW_TIME"
    - "FROM_TZ"
    - "TO_TZ"
    - "AT"
    - "TIME"
    - "ZONE"
  
  # 숫자 함수
  number_functions:
    - "ROUND"
    - "TRUNC"
    - "MOD"
    - "POWER"
    - "SQRT"
    - "ABS"
    - "CEIL"
    - "FLOOR"
    - "SIGN"
    - "SIN"
    - "COS"
    - "TAN"
    - "ASIN"
    - "ACOS"
    - "ATAN"
    - "ATAN2"
    - "SINH"
    - "COSH"
    - "TANH"
    - "EXP"
    - "LN"
    - "LOG"
    - "BITAND"
    - "REMAINDER"
  
  # 변환 함수
  conversion_functions:
    - "TO_NUMBER"
    - "TO_CHAR"
    - "TO_DATE"
    - "TO_TIMESTAMP"
    - "TO_DSINTERVAL"
    - "TO_YMINTERVAL"
    - "CAST"
    - "CONVERT"
    - "HEXTORAW"
    - "RAWTOHEX"
    - "CHARTOROWID"
    - "ROWIDTOCHAR"
    - "TO_LOB"
    - "TO_NCLOB"
    - "TO_CLOB"
    - "TO_BLOB"
    - "TO_RAW"
    - "TO_SINGLE_BYTE"
    - "TO_MULTI_BYTE"
  
  # NULL 처리 함수
  null_functions:
    - "NVL"
    - "NVL2"
    - "COALESCE"
    - "NULLIF"
    - "LNNVL"
    - "NANVL"
  
  # 기타 함수
  other_functions:
    - "DECODE"
    - "CASE"
    - "GREATEST"
    - "LEAST"
    - "USERENV"
    - "SYS_CONTEXT"
    - "SYS_GUID"
    - "SYS_EXTRACT_UTC"
    - "TZ_OFFSET"
    - "FROM_TZ"
    - "TO_TZ"
    - "AT"
    - "TIME"
    - "ZONE"
    - "BFILENAME"
    - "EMPTY_BLOB"
    - "EMPTY_CLOB"
    - "EMPTY_NCLOB"

# Oracle SQL 패턴
oracle_sql_patterns:
  # DDL 패턴
  ddl_patterns:
    create_table_pattern: "CREATE\\s+(?:GLOBAL\\s+TEMPORARY\\s+)?TABLE\\s+(\\w+(?:\\.\\w+)?)\\s*\\("
    create_view_pattern: "CREATE\\s+(?:OR\\s+REPLACE\\s+)?(?:FORCE\\s+|NOFORCE\\s+)?VIEW\\s+(\\w+(?:\\.\\w+)?)\\s+AS"
    create_index_pattern: "CREATE\\s+(?:UNIQUE\\s+)?(?:BITMAP\\s+)?INDEX\\s+(\\w+(?:\\.\\w+)?)\\s+ON\\s+(\\w+(?:\\.\\w+)?)"
    create_sequence_pattern: "CREATE\\s+SEQUENCE\\s+(\\w+(?:\\.\\w+)?)"
    create_procedure_pattern: "CREATE\\s+(?:OR\\s+REPLACE\\s+)?PROCEDURE\\s+(\\w+(?:\\.\\w+)?)\\s*\\("
    create_function_pattern: "CREATE\\s+(?:OR\\s+REPLACE\\s+)?FUNCTION\\s+(\\w+(?:\\.\\w+)?)\\s*\\("
    create_package_pattern: "CREATE\\s+(?:OR\\s+REPLACE\\s+)?PACKAGE\\s+(\\w+(?:\\.\\w+)?)"
    create_trigger_pattern: "CREATE\\s+(?:OR\\s+REPLACE\\s+)?TRIGGER\\s+(\\w+(?:\\.\\w+)?)"
    alter_table_pattern: "ALTER\\s+TABLE\\s+(\\w+(?:\\.\\w+)?)\\s+"
    drop_table_pattern: "DROP\\s+TABLE\\s+(\\w+(?:\\.\\w+)?)"
    drop_view_pattern: "DROP\\s+VIEW\\s+(\\w+(?:\\.\\w+)?)"
    drop_index_pattern: "DROP\\s+INDEX\\s+(\\w+(?:\\.\\w+)?)"
    drop_sequence_pattern: "DROP\\s+SEQUENCE\\s+(\\w+(?:\\.\\w+)?)"
    drop_procedure_pattern: "DROP\\s+PROCEDURE\\s+(\\w+(?:\\.\\w+)?)"
    drop_function_pattern: "DROP\\s+FUNCTION\\s+(\\w+(?:\\.\\w+)?)"
    drop_package_pattern: "DROP\\s+PACKAGE\\s+(\\w+(?:\\.\\w+)?)"
    drop_trigger_pattern: "DROP\\s+TRIGGER\\s+(\\w+(?:\\.\\w+)?)"
  
  # DML 패턴
  dml_patterns:
    select_pattern: "SELECT\\s+.*?\\s+FROM\\s+(\\w+(?:\\.\\w+)?)"
    insert_pattern: "INSERT\\s+INTO\\s+(\\w+(?:\\.\\w+)?)\\s*\\("
    update_pattern: "UPDATE\\s+(\\w+(?:\\.\\w+)?)\\s+SET"
    delete_pattern: "DELETE\\s+FROM\\s+(\\w+(?:\\.\\w+)?)"
    merge_pattern: "MERGE\\s+INTO\\s+(\\w+(?:\\.\\w+)?)\\s+USING"
  
  # 조인 패턴
  join_patterns:
    inner_join_pattern: "INNER\\s+JOIN\\s+(\\w+(?:\\.\\w+)?)"
    left_join_pattern: "LEFT\\s+(?:OUTER\\s+)?JOIN\\s+(\\w+(?:\\.\\w+)?)"
    right_join_pattern: "RIGHT\\s+(?:OUTER\\s+)?JOIN\\s+(\\w+(?:\\.\\w+)?)"
    full_join_pattern: "FULL\\s+(?:OUTER\\s+)?JOIN\\s+(\\w+(?:\\.\\w+)?)"
    cross_join_pattern: "CROSS\\s+JOIN\\s+(\\w+(?:\\.\\w+)?)"
    natural_join_pattern: "NATURAL\\s+JOIN\\s+(\\w+(?:\\.\\w+)?)"
  
  # 서브쿼리 패턴
  subquery_patterns:
    exists_pattern: "EXISTS\\s*\\("
    in_pattern: "IN\\s*\\("
    not_in_pattern: "NOT\\s+IN\\s*\\("
    any_pattern: "ANY\\s*\\("
    some_pattern: "SOME\\s*\\("
    all_pattern: "ALL\\s*\\("
  
  # 분석 함수 패턴
  analytical_patterns:
    over_pattern: "OVER\\s*\\("
    partition_by_pattern: "PARTITION\\s+BY\\s+"
    order_by_pattern: "ORDER\\s+BY\\s+"
    window_pattern: "WINDOW\\s+"
    range_pattern: "RANGE\\s+"
    rows_pattern: "ROWS\\s+"
  
  # 정규식 패턴
  regex_patterns:
    table_name_pattern: "\\b\\w+(?:\\.\\w+)?\\b"
    column_name_pattern: "\\b\\w+\\b"
    function_call_pattern: "\\w+\\s*\\("
    parameter_pattern: "\\$\\{.*?\\}|\\?|:[\\w]+"
    comment_pattern: "--.*$|/\\*.*?\\*/"

# Oracle SQL 데이터 타입
oracle_data_types:
  # 문자 타입
  character_types:
    - "CHAR"
    - "VARCHAR2"
    - "NCHAR"
    - "NVARCHAR2"
    - "CLOB"
    - "NCLOB"
    - "LONG"
  
  # 숫자 타입
  number_types:
    - "NUMBER"
    - "INTEGER"
    - "INT"
    - "SMALLINT"
    - "FLOAT"
    - "BINARY_FLOAT"
    - "BINARY_DOUBLE"
    - "REAL"
    - "DECIMAL"
    - "NUMERIC"
  
  # 날짜 타입
  date_types:
    - "DATE"
    - "TIMESTAMP"
    - "TIMESTAMP WITH TIME ZONE"
    - "TIMESTAMP WITH LOCAL TIME ZONE"
    - "INTERVAL YEAR TO MONTH"
    - "INTERVAL DAY TO SECOND"
  
  # 이진 타입
  binary_types:
    - "RAW"
    - "LONG RAW"
    - "BLOB"
    - "BFILE"
  
  # 기타 타입
  other_types:
    - "ROWID"
    - "UROWID"
    - "XMLType"
    - "JSON"
    - "JSON_ARRAY"
    - "JSON_OBJECT"
    - "JSON_SCALAR"

# Oracle SQL 제약조건
oracle_constraints:
  - "PRIMARY KEY"
  - "FOREIGN KEY"
  - "UNIQUE"
  - "CHECK"
  - "NOT NULL"
  - "REFERENCES"
  - "ON DELETE CASCADE"
  - "ON DELETE SET NULL"
  - "ON UPDATE CASCADE"
  - "ON UPDATE SET NULL"

# Oracle SQL 힌트
oracle_hints:
  - "ALL_ROWS"
  - "FIRST_ROWS"
  - "RULE"
  - "CHOOSE"
  - "INDEX"
  - "INDEX_ASC"
  - "INDEX_DESC"
  - "INDEX_COMBINE"
  - "INDEX_FFS"
  - "INDEX_JOIN"
  - "INDEX_SS"
  - "INDEX_SS_ASC"
  - "INDEX_SS_DESC"
  - "FULL"
  - "HASH"
  - "HASH_AJ"
  - "HASH_SJ"
  - "MERGE"
  - "MERGE_AJ"
  - "MERGE_SJ"
  - "NESTED_LOOPS"
  - "USE_CONCAT"
  - "NO_EXPAND"
  - "REWRITE"
  - "NO_REWRITE"
  - "UNNEST"
  - "NO_UNNEST"
  - "PUSH_PRED"
  - "NO_PUSH_PRED"
  - "PUSH_SUBQ"
  - "NO_PUSH_SUBQ"
  - "ORDERED"
  - "STAR_TRANSFORMATION"
  - "NO_STAR_TRANSFORMATION"
  - "FACT"
  - "NO_FACT"
  - "CUBE_GB"
  - "NO_CUBE_GB"
  - "GBY_CONC_ROLLUP"
  - "NO_GBY_CONC_ROLLUP"
  - "PARALLEL"
  - "NO_PARALLEL"
  - "PARALLEL_INDEX"
  - "NO_PARALLEL_INDEX"
  - "PQ_DISTRIBUTE"
  - "NO_PQ_DISTRIBUTE"
  - "PQ_MAP"
  - "NO_PQ_MAP"
  - "PQ_SKEW"
  - "NO_PQ_SKEW"
  - "PQ_FILTER"
  - "NO_PQ_FILTER"
  - "PQ_REPLICATE"
  - "NO_PQ_REPLICATE"
  - "PQ_BROADCAST"
  - "NO_PQ_BROADCAST"
  - "PQ_RANDOM"
  - "NO_PQ_RANDOM"
  - "PQ_HASH"
  - "NO_PQ_HASH"
  - "PQ_RANGE"
  - "NO_PQ_RANGE"
  - "PQ_DISTRIBUTE_WINDOW"
  - "NO_PQ_DISTRIBUTE_WINDOW"
  - "PQ_DISTRIBUTE_JOIN"
  - "NO_PQ_DISTRIBUTE_JOIN"
  - "PQ_DISTRIBUTE_GROUP_BY"
  - "NO_PQ_DISTRIBUTE_GROUP_BY"
  - "PQ_DISTRIBUTE_ORDER_BY"
  - "NO_PQ_DISTRIBUTE_ORDER_BY"
  - "PQ_DISTRIBUTE_DISTINCT"
  - "NO_PQ_DISTRIBUTE_DISTINCT"
  - "PQ_DISTRIBUTE_UNION"
  - "NO_PQ_DISTRIBUTE_UNION"
  - "PQ_DISTRIBUTE_INTERSECT"
  - "NO_PQ_DISTRIBUTE_INTERSECT"
  - "PQ_DISTRIBUTE_MINUS"
  - "NO_PQ_DISTRIBUTE_MINUS"
  - "PQ_DISTRIBUTE_CONCAT"
  - "NO_PQ_DISTRIBUTE_CONCAT"
  - "PQ_DISTRIBUTE_PIVOT"
  - "NO_PQ_DISTRIBUTE_PIVOT"
  - "PQ_DISTRIBUTE_UNPIVOT"
  - "NO_PQ_DISTRIBUTE_UNPIVOT"
  - "PQ_DISTRIBUTE_MODEL"
  - "NO_PQ_DISTRIBUTE_MODEL"
  - "PQ_DISTRIBUTE_ANALYTIC"
  - "NO_PQ_DISTRIBUTE_ANALYTIC"
  - "PQ_DISTRIBUTE_WINDOW_FUNC"
  - "NO_PQ_DISTRIBUTE_WINDOW_FUNC"
  - "PQ_DISTRIBUTE_AGGREGATE"
  - "NO_PQ_DISTRIBUTE_AGGREGATE"
  - "PQ_DISTRIBUTE_GROUPING"
  - "NO_PQ_DISTRIBUTE_GROUPING"
  - "PQ_DISTRIBUTE_ROLLUP"
  - "NO_PQ_DISTRIBUTE_ROLLUP"
  - "PQ_DISTRIBUTE_CUBE"
  - "NO_PQ_DISTRIBUTE_CUBE"
  - "PQ_DISTRIBUTE_GROUPING_SETS"
  - "NO_PQ_DISTRIBUTE_GROUPING_SETS"
  - "PQ_DISTRIBUTE_PIVOT_GB"
  - "NO_PQ_DISTRIBUTE_PIVOT_GB"
  - "PQ_DISTRIBUTE_UNPIVOT_GB"
  - "NO_PQ_DISTRIBUTE_UNPIVOT_GB"
  - "PQ_DISTRIBUTE_MODEL_GB"
  - "NO_PQ_DISTRIBUTE_MODEL_GB"
  - "PQ_DISTRIBUTE_ANALYTIC_GB"
  - "NO_PQ_DISTRIBUTE_ANALYTIC_GB"
  - "PQ_DISTRIBUTE_WINDOW_FUNC_GB"
  - "NO_PQ_DISTRIBUTE_WINDOW_FUNC_GB"
  - "PQ_DISTRIBUTE_AGGREGATE_GB"
  - "NO_PQ_DISTRIBUTE_AGGREGATE_GB"
  - "PQ_DISTRIBUTE_GROUPING_GB"
  - "NO_PQ_DISTRIBUTE_GROUPING_GB"
  - "PQ_DISTRIBUTE_ROLLUP_GB"
  - "NO_PQ_DISTRIBUTE_ROLLUP_GB"
  - "PQ_DISTRIBUTE_CUBE_GB"
  - "NO_PQ_DISTRIBUTE_CUBE_GB"
  - "PQ_DISTRIBUTE_GROUPING_SETS_GB"
  - "NO_PQ_DISTRIBUTE_GROUPING_SETS_GB"

# Oracle SQL 예외 처리
oracle_exception_handling:
  - "EXCEPTION"
  - "WHEN"
  - "THEN"
  - "ELSE"
  - "END"
  - "RAISE"
  - "RAISE_APPLICATION_ERROR"
  - "SQLCODE"
  - "SQLERRM"
  - "OTHERS"
  - "NO_DATA_FOUND"
  - "TOO_MANY_ROWS"
  - "DUP_VAL_ON_INDEX"
  - "VALUE_ERROR"
  - "INVALID_NUMBER"
  - "ZERO_DIVIDE"
  - "CURSOR_ALREADY_OPEN"
  - "INVALID_CURSOR"
  - "PROGRAM_ERROR"
  - "STORAGE_ERROR"
  - "TIMEOUT_ON_RESOURCE"
  - "LOGIN_DENIED"
  - "NOT_LOGGED_ON"
  - "TRANSACTION_BACKED_OUT"
  - "ACCESS_INTO_NULL"
  - "COLLECTION_IS_NULL"
  - "SUBSCRIPT_BEYOND_COUNT"
  - "SUBSCRIPT_OUTSIDE_LIMIT"
  - "CASE_NOT_FOUND"
  - "SELF_IS_NULL"
  - "INVALID_ROWID"
  - "ROWTYPE_MISMATCH"
  - "SYS_INVALID_ROWID"
  - "CURSOR_ALREADY_OPEN"
  - "INVALID_CURSOR"
  - "PROGRAM_ERROR"
  - "STORAGE_ERROR"
  - "TIMEOUT_ON_RESOURCE"
  - "LOGIN_DENIED"
  - "NOT_LOGGED_ON"
  - "TRANSACTION_BACKED_OUT"
  - "ACCESS_INTO_NULL"
  - "COLLECTION_IS_NULL"
  - "SUBSCRIPT_BEYOND_COUNT"
  - "SUBSCRIPT_OUTSIDE_LIMIT"
  - "CASE_NOT_FOUND"
  - "SELF_IS_NULL"
  - "INVALID_ROWID"
  - "ROWTYPE_MISMATCH"
  - "SYS_INVALID_ROWID"

# Oracle SQL 관계 타입
oracle_relationship_types:
  - "QUERIES"
  - "JOINS"
  - "REFERENCES"
  - "CONSTRAINS"
  - "INDEXES"
  - "TRIGGERS"
  - "PROCEDURES"
  - "FUNCTIONS"
  - "PACKAGES"
  - "VIEWS"
  - "SEQUENCES"
  - "SYNONYMS"
  - "MATERIALIZED_VIEWS"
  - "PARTITIONS"
  - "SUBPARTITIONS"
